Fix engine replica range
kennedybg/courtsdk pull request #8
Opened 2019-07-15 18:45 UTC by kennedybg

Fix engine replica range

2019-07-16 18:09 UTC, DanielASCarmo approved these changes

2019-07-17 13:44 UTC, thiagopnobre requested changes

2019-07-17 13:44 UTC, thiagopnobre commented on engine.go
> +	if lastRange > -1 {
Pq dessa condicional aqui? Não vejo um cenário em que o `LastGoRoutineRange` vai ser menor que zero, a não ser se alguém configurar o `Start` pra um valor negativo intencionalmente.

Tenho a impressão que isso está adicionando complexidade desnecessária e está criando um comportamento inesperado/obscuro, já que se espera que o `Start` comece sempre no valor que foi definido na engine, independente de que número seja esse.

Além disso, o comportamento do `Start` nesse caso, está funcionando com uma regra diferente para a execução concorrente e para a sequencial, já que a sequencial pode pode iniciar com um `Start` negativo e a concorrente não. O que ao meu ver é uma inconsistência.

2019-07-17 17:37 UTC, thiagopnobre approved these changes

2019-07-17 17:38 UTC, merged